tasks:
  - name: distinct production
    init: docker-compose -f ./src/docker-compose.yaml build
    command: docker-compose -f ./src/docker-compose.yaml up

ports:
  - port: 9080
    onOpen: open-browser
  - port: 9090
    onOpen: ignore
  - port: 9070
    onOpen: ignore
