image:
  file: .gitpod.Dockerfile
  context: ./

tasks:
  - name: distinct-core-api
    init: cd /workspace/DISTINCT/src/distinct-core && pip3 install -r requirements.txt
    command: cd /workspace/DISTINCT/src/distinct-core && python3 distinct-core.py
    env:
      VERBOSITY: DEBUG
      DISTINCT_DB: mongodb://localhost:27017/
      DISTINCT_BROWSER: http://localhost:9081
      PYTHON_APP_MODE: prod

  - name: distinct-core-gui
    init: cd /workspace/DISTINCT/src/distinct-core/gui && npm install && npm run build
    command: cd /workspace/DISTINCT/src/distinct-core/gui && npm run serve
    env:
      VUE_APP_MODE: prod

  - name: distinct-browser-api
    init: cd /workspace/DISTINCT/src/distinct-browser/distinct-browser-api && pip3 install -r requirements.txt
    command: cd /workspace/DISTINCT/src/distinct-browser/distinct-browser-api && python3 distinct-browser.py
    env:
      VERBOSITY: DEBUG
      DISTINCT_DB: mongodb://localhost:27017/
      DISTINCT_CORE: http://localhost:9080

  - name: distinct-browser-mitmproxy
    init: cd /workspace/DISTINCT/src/distinct-browser/mitmproxy && pip3 install -r requirements.txt

  - name: distinct-browser-vnc
    init: echo $VNCPWD | vncpasswd -f > ~/.vnc/passwd && chmod 600 ~/.vnc/passwd
    command: vncserver :0 -rfbport $VNCPORT -geometry $VNCDISPLAY -depth $VNCDEPTH -localhost
    env:
      USER: gitpod
      VNCPORT: 9091
      VNCPWD: changeme
      VNCDISPLAY: 1920x1080
      VNCDEPTH: 16

  - name: distinct-browser-novnc
    command: /usr/share/novnc/utils/launch.sh --listen $NOVNCPORT --vnc localhost:$VNCPORT
    env:
      VNCPORT: 9091
      NOVNCPORT: 9090

  - name: distinct-db
    command: mongod --dbpath /workspace/distinct-db-data

  - name: git-lfs-distinct-chromium
    init: cd /workspace/DISTINCT && git lfs pull && cp ./src/distinct-browser/distinct-chromium.zip /distinct-chromium.zip && unzip /distinct-chromium.zip -d /

ports:
  # distinct-core-api
  - port: 9080
    onOpen: ignore
  # distinct-browser-api
  - port: 9081
    onOpen: ignore
  # distinct-core-gui
  - port: 3000
    onOpen: open-browser
  # distinct-browser-novnc
  - port: 9090
    onOpen: open-browser
  # distinct-browser-vnc
  - port: 9091
    onOpen: ignore
