tasks:
  - init: docker-compose -f ./src/docker-compose.yml build
  - command: docker-compose -f ./src/docker-compose.yml up

ports:
  - port: 8080
    onOpen: open-browser
  - port: 9090
    onOpen: ignore

vscode:
  extensions:
    - ms-azuretools.vscode-docker
