image:
  file: .gitpod.Dockerfile
  context: ./

tasks:
  - name: distinct-core-api
    init: cd /workspace/DISTINCT/src/distinct-core && pip3 install -r requirements.txt
    command: cd /workspace/DISTINCT/src/distinct-core && python3 distinct-core.py
    env:
      VERBOSITY: DEBUG
      DISTINCT_DB: mongodb://localhost:27017/
      DISTINCT_BROWSER: http://localhost:9081
      PYTHON_APP_MODE: prod

  - name: distinct-core-gui
    init: cd /workspace/DISTINCT/src/distinct-core/gui && npm install && npm run build
    command: cd /workspace/DISTINCT/src/distinct-core/gui && npm run serve
    env:
      VUE_APP_MODE: prod

  - name: distinct-browser-api
    init: cd /workspace/DISTINCT/src/distinct-browser/distinct-browser-api && pip3 install -r requirements.txt
    command: cd /workspace/DISTINCT/src/distinct-browser/distinct-browser-api && python3 distinct-browser.py
    env:
      VERBOSITY: DEBUG
      DISTINCT_DB: mongodb://localhost:27017/
      DISTINCT_CORE: http://localhost:9080

  - name: distinct-browser-mitmproxy
    init: cd /workspace/DISTINCT/src/distinct-browser/mitmproxy && pip3 install -r requirements.txt

  - name: distinct-browser-vnc
    init: >
      mkdir -p ~/.vnc &&
      touch ~/.vnc/passwd &&
      echo $VNCPWD | vncpasswd -f > ~/.vnc/passwd &&
      chmod 600 ~/.vnc/passwd &&
      echo -e '#!/bin/sh \n
      xrdb $HOME/.Xresources \n
      xsetroot -solid grey \n
      #x-terminal-emulator -geometry 80x24+10+10 -ls -title "$VNCDESKTOP Desktop" & \n
      #x-window-manager & \n
      # Fix to make GNOME work \n
      export XKL_XMODMAP_DISABLE=1 \n
      /etc/X11/Xsession \n
      startxfce4 &
      ' > ~/.vnc/xstartup
    command: vncserver :0 -rfbport $VNCPORT -geometry $VNCDISPLAY -depth $VNCDEPTH -localhost
    env:
      USER: gitpod
      VNCPORT: 9091
      VNCPWD: changeme
      VNCDISPLAY: 1920x1080
      VNCDEPTH: 16

  - name: distinct-browser-novnc
    command: /usr/share/novnc/utils/launch.sh --listen $NOVNCPORT --vnc localhost:$VNCPORT
    env:
      VNCPORT: 9091
      NOVNCPORT: 9090

  - name: distinct-db
    command: mongod --dbpath /app/data/db

  - name: git-lfs-distinct-chromium
    init: cd /workspace/DISTINCT && git lfs pull && sudo cp ./src/distinct-browser/distinct-chromium.zip /distinct-chromium.zip && unzip /distinct-chromium.zip -d /

ports:
  # distinct-core-api
  - port: 9080
    onOpen: ignore
  # distinct-browser-api
  - port: 9081
    onOpen: ignore
  # distinct-core-gui
  - port: 3000
    onOpen: open-browser
  # distinct-browser-novnc
  - port: 9090
    onOpen: open-browser
  # distinct-browser-vnc
  - port: 9091
    onOpen: ignore
