version: '3'

services:
  distinct-core:
    build: ./distinct-core
    container_name: distinct-core
    restart: always
    ports:
      - "8080:8080" # API
    networks:
      - distinct-net
    volumes:
      - distinct-core-data:/app/data
  distinct-browser:
    build: ./distinct-browser
    container_name: distinct-browser
    restart: always
    depends_on:
      - distinct-core
    ports:
      - "9090:9090" # NoVNC
    networks:
      - distinct-net
    volumes:
      - distinct-browser-data:/app/data

networks:
  distinct-net:
    driver: bridge

volumes:
  distinct-browser-data:
  distinct-core-data:
