version: '3'

services:
  distinct-core:
    build: ./distinct-core
    container_name: distinct-core
    restart: always
    ports:
      - "9080:8080"
    networks:
      - distinct-net
    volumes:
      - distinct-core-data:/app/data
    environment:
      VERBOSITY: ${VERBOSITY}
  distinct-browser:
    build: ./distinct-browser
    container_name: distinct-browser
    restart: always
    depends_on:
      - distinct-core
    ports:
      - "9090:9090"
    networks:
      - distinct-net
    volumes:
      - distinct-browser-data:/app/data
    environment:
      VERBOSITY: ${VERBOSITY}
      VNCPWD: ${VNCPWD}
      GOOGLE_USERNAME: ${GOOGLE_USERNAME}
      GOOGLE_PASSWORD: ${GOOGLE_PASSWORD}
      FACEBOOK_USERNAME: ${FACEBOOK_USERNAME}
      FACEBOOK_PASSWORD: ${FACEBOOK_PASSWORD}
      APPLE_USERNAME: ${APPLE_USERNAME}
      APPLE_PASSWORD: ${APPLE_PASSWORD}
      APPLE_2FA: ${APPLE_2FA}

networks:
  distinct-net:
    driver: bridge

volumes:
  distinct-browser-data:
  distinct-core-data:
