services:
  distinct-demo-core:
    build:
      context: ./distinct-core
      args:
        MODE: demo
    container_name: distinct-demo-core
    restart: always
    depends_on:
      distinct-demo-db-import:
        condition: service_completed_successfully
    ports:
      - "127.0.0.1:9080:9080"
    networks:
      - distinct-demo-net
    volumes:
      - distinct-demo-core-data:/app/data
    environment:
      DISTINCT_DB: mongodb://distinct-demo-db:27017
      VERBOSITY: ${VERBOSITY}

  distinct-demo-db-import:
    build: ../demo-data
    container_name: distinct-demo-db-import
    depends_on:
      distinct-demo-db:
        condition: service_healthy
    networks:
      - distinct-demo-net
    environment:
      DISTINCT_DB: mongodb://distinct-demo-db:27017

  distinct-demo-db:
    image: mongo:4.4.6
    container_name: distinct-demo-db
    restart: always
    healthcheck:
      test: ["CMD", "mongo", "--quiet", "--eval", "db.adminCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - distinct-demo-net
    volumes:
      - distinct-demo-db-data:/data/db

  distinct-demo-db-explorer:
    image: mongo-express:0.54.0
    container_name: distinct-demo-db-explorer
    restart: always
    depends_on:
      - distinct-demo-db
    ports:
      - "127.0.0.1:9070:8081"
    networks:
      - distinct-demo-net
    environment:
      - ME_CONFIG_MONGODB_SERVER=distinct-demo-db

  distinct-demo-test:
    build: ../test
    container_name: distinct-demo-test
    restart: always
    ports:
      - "127.0.0.1:9060:80"
    networks:
      - distinct-demo-net

networks:
  distinct-demo-net:
    driver: bridge

volumes:
  distinct-demo-core-data:
  distinct-demo-db-data:
